/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Presentacion;

import DTOs.PeliculaDTO;
import Negocio.CinepolisBO;
import entidades.Pelicula;
import java.awt.CardLayout;
import java.awt.Image;
import java.io.IOException;
import java.sql.SQLException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JPanel;

/**
 *
 * @author diana
 */
public class Cartelera extends javax.swing.JFrame {

    CinepolisBO cinepolisBO = new CinepolisBO();
    private int pagina = 1;
    private int LIMITE = 1;
    private List<PeliculaDTO> peliculas;
    private CinepolisBO negocio = new CinepolisBO();
    private CardLayout cardLayout;
    private JPanel mainPanel;

    /**
     * Creates new form catalogoPeliculas
     */
    public Cartelera(String nombreSucursal) {
        initComponents();
        this.setLocationRelativeTo(this);
        this.setSize(955, 580);

        try {
            peliculas = negocio.PeliculasPOrSucursal(nombreSucursal);
        } catch (SQLException ex) {
            Logger.getLogger(Cartelera.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    public Cartelera() {

        initComponents();
        this.setLocationRelativeTo(this);
        this.setSize(955, 580);
        try {
            peliculas = negocio.TodasLasPeliculas();
            
            rellenarCartelera(peliculas, 6);
        } catch (SQLException ex) {
            Logger.getLogger(Cartelera.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(Cartelera.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFileChooser1 = new javax.swing.JFileChooser();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        ComboBoxGenero = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        btnAtras = new javax.swing.JButton();
        btnSiguiente = new javax.swing.JButton();
        numeroPagina = new javax.swing.JTextField();
        Pelicula1 = new javax.swing.JButton();
        Pelicula2 = new javax.swing.JButton();
        Pelicula3 = new javax.swing.JButton();
        Pelicula4 = new javax.swing.JButton();
        Pelicula5 = new javax.swing.JButton();
        Pelicula6 = new javax.swing.JButton();
        btnMenu = new javax.swing.JMenuBar();
        jMenu2 = new javax.swing.JMenu();
        btnVerSucursales = new javax.swing.JRadioButtonMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jRadioButtonMenuItem2 = new javax.swing.JRadioButtonMenuItem();
        jMenu1 = new javax.swing.JMenu();
        jRadioButtonMenuItem1 = new javax.swing.JRadioButtonMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setForeground(new java.awt.Color(12, 33, 63));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(12, 33, 63));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 610, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 40, 610));

        jPanel3.setBackground(new java.awt.Color(12, 33, 63));

        ComboBoxGenero.setBackground(new java.awt.Color(12, 33, 63));
        ComboBoxGenero.setFont(new java.awt.Font("Sitka Text", 0, 12)); // NOI18N
        ComboBoxGenero.setForeground(new java.awt.Color(255, 255, 255));
        ComboBoxGenero.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Terror", "Comedia", "Ciencia Ficcion", "Drama ", "Musical", " " }));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(774, Short.MAX_VALUE)
                .addComponent(ComboBoxGenero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(12, Short.MAX_VALUE)
                .addComponent(ComboBoxGenero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 0, 910, 40));

        jLabel1.setFont(new java.awt.Font("Serif", 0, 36)); // NOI18N
        jLabel1.setText("Cartelera ");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 40, -1, -1));

        btnAtras.setBackground(new java.awt.Color(12, 33, 63));
        btnAtras.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btnAtras.setText("←");
        btnAtras.setContentAreaFilled(false);
        btnAtras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtrasActionPerformed(evt);
            }
        });
        jPanel1.add(btnAtras, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 560, -1, -1));

        btnSiguiente.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btnSiguiente.setText("→");
        btnSiguiente.setContentAreaFilled(false);
        btnSiguiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSiguienteActionPerformed(evt);
            }
        });
        jPanel1.add(btnSiguiente, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 570, -1, -1));

        numeroPagina.setText("1");
        jPanel1.add(numeroPagina, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 580, 20, -1));

        Pelicula1.setText("jButton1");
        jPanel1.add(Pelicula1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 130, 120, 180));

        Pelicula2.setText("jButton1");
        jPanel1.add(Pelicula2, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 130, 120, 180));

        Pelicula3.setText("jButton1");
        jPanel1.add(Pelicula3, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 130, 120, 180));

        Pelicula4.setText("jButton1");
        jPanel1.add(Pelicula4, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 350, 120, 180));

        Pelicula5.setText("jButton1");
        jPanel1.add(Pelicula5, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 350, 120, 180));

        Pelicula6.setText("jButton1");
        jPanel1.add(Pelicula6, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 350, 120, 180));

        jMenu2.setText("Sucursales");

        btnVerSucursales.setSelected(true);
        btnVerSucursales.setText("Ver Sucursales");
        btnVerSucursales.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerSucursalesActionPerformed(evt);
            }
        });
        jMenu2.add(btnVerSucursales);

        btnMenu.add(jMenu2);

        jMenu3.setText("Funciones");

        jRadioButtonMenuItem2.setSelected(true);
        jRadioButtonMenuItem2.setText("Ver Funciones");
        jMenu3.add(jRadioButtonMenuItem2);

        btnMenu.add(jMenu3);

        jMenu1.setText("Salas");

        jRadioButtonMenuItem1.setSelected(true);
        jRadioButtonMenuItem1.setText("Ver Salas");
        jRadioButtonMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jRadioButtonMenuItem1);

        btnMenu.add(jMenu1);

        setJMenuBar(btnMenu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jRadioButtonMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonMenuItem1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButtonMenuItem1ActionPerformed

    private void btnSiguienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSiguienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSiguienteActionPerformed

    private void btnAtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtrasActionPerformed
        // TODO add your handling code here:
        if (pagina > 1) {
            pagina--;

        }
    }//GEN-LAST:event_btnAtrasActionPerformed

    private void btnVerSucursalesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerSucursalesActionPerformed
        // TODO add your handling code here:
        Sucursales sucursales = new Sucursales();
        sucursales.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnVerSucursalesActionPerformed

    public void rellenarCartelera(List<PeliculaDTO> peliculas, int limite) throws IOException {
        JButton[] botones = {this.Pelicula1, this.Pelicula2, this.Pelicula3, this.Pelicula4, this.Pelicula5, this.Pelicula6};
        int contador = 0;
        for (PeliculaDTO pelicula : peliculas) {
            if (contador < limite ) {

                Image img = ImageIO.read(getClass().getResource("ruta/a/tu/" + pelicula.getTitulo() + ".png"));

                botones[contador].setIcon(new ImageIcon(img));
                contador++;
            }

        }

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Cartelera.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Cartelera.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Cartelera.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Cartelera.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new Cartelera(negocio).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> ComboBoxGenero;
    private javax.swing.JButton Pelicula1;
    private javax.swing.JButton Pelicula2;
    private javax.swing.JButton Pelicula3;
    private javax.swing.JButton Pelicula4;
    private javax.swing.JButton Pelicula5;
    private javax.swing.JButton Pelicula6;
    private javax.swing.JButton btnAtras;
    private javax.swing.JMenuBar btnMenu;
    private javax.swing.JButton btnSiguiente;
    private javax.swing.JRadioButtonMenuItem btnVerSucursales;
    private javax.swing.JFileChooser jFileChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem1;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem2;
    private javax.swing.JTextField numeroPagina;
    // End of variables declaration//GEN-END:variables
}
